version: '3.7'

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - database:/var/lib/mysql
    networks:
      - main

  loader:
    build:
      context: .
    depends_on:
      - db
    networks:
      - main
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: db
      SF_USERNAME: "${SF_USERNAME}"
      SF_PASSWORD: "${SF_PASSWORD}"
      SF_SECURITY_TOKEN: "${SF_SECURITY_TOKEN}"
      CONFIG_FILE: ./src/config.json
    volumes:
      - files:/app/tmp

volumes:
  database:
  files:

networks:
  main:

